# Generated by Django 4.1.2 on 2022-10-21 10:02

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_application_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий', max_length=1000),
        ),
        migrations.AddField(
            model_name='application',
            name='img',
            field=models.ImageField(max_length=254, null=True, upload_to=catalog.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])]),
        ),
    ]
