# Generated by Django 3.2.16 on 2022-11-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_application_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия'),
        ),
    ]
